[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[lib]
# crate-type = ["cdylib"]

[dependencies]
enum-iterator = "1.4.1"
rand = "0.8.5"
getrandom = { version = "0.2", features = ["js"] }
h3o = "0.4.0"

[profile.release]
debug = true